package main

import (
	"fmt"
	"image"
	"image/color"
	_ "image/jpeg"
	"image/png"
	_ "image/png"
	"io"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
)

const userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

var (
	styleRe    = regexp.MustCompile(`(?s)<style[^>]*>(.*?)</style>`)
	posRe      = regexp.MustCompile(`\.([A-Za-z0-9_-]+)\s*\{[^}]*background-position:\s*(-?\d+)px\s+(-?\d+)px`)
	stockRe    = regexp.MustCompile(`(?s)var cards_stock = (\[.*?\]);`)
	quantCssRe = regexp.MustCompile(`"quantCss":"([^"]*)"`)
	atlasRe    = regexp.MustCompile(`url\(([^)]*imgunid[^)]*)\)`)
)

func main() {
	if len(os.Args) < 2 {
		usage()
	}
	switch os.Args[1] {
	case "montage":
		if len(os.Args) != 3 {
			usage()
		}
		montage(os.Args[2])
	case "gen":
		if len(os.Args) != 23 {
			usage()
		}
		gen(os.Args[2], os.Args[3:])
	default:
		usage()
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage:")
	fmt.Fprintln(os.Stderr, "  spritecal montage <cardPageURL>   # dump montage.png + positions to label")
	fmt.Fprintln(os.Stderr, "  spritecal gen <atlasURL|file> x0 y0 x1 y1 ... x9 y9   # emit digitTemplates literal")
	os.Exit(2)
}

func fetch(url string) []byte {
	if strings.HasPrefix(url, "//") {
		url = "https:" + url
	}
	req, _ := http.NewRequest(http.MethodGet, url, nil)
	req.Header.Set("User-Agent", userAgent)
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetch:", err)
		os.Exit(1)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	return body
}

func loadImage(src string) image.Image {
	var data []byte
	if strings.HasPrefix(src, "http") || strings.HasPrefix(src, "//") {
		data = fetch(src)
	} else {
		var err error
		if data, err = os.ReadFile(src); err != nil {
			fmt.Fprintln(os.Stderr, "read:", err)
			os.Exit(1)
		}
	}
	img, _, err := image.Decode(strings.NewReader(string(data)))
	if err != nil {
		fmt.Fprintln(os.Stderr, "decode image:", err)
		os.Exit(1)
	}
	return img
}

func montage(pageURL string) {
	html := fetch(pageURL)
	style := styleRe.FindSubmatch(html)
	if style == nil {
		fmt.Fprintln(os.Stderr, "no <style> block")
		os.Exit(1)
	}
	pos := map[string][2]int{}
	for _, m := range posRe.FindAllSubmatch(style[1], -1) {
		x, _ := strconv.Atoi(string(m[2]))
		y, _ := strconv.Atoi(string(m[3]))
		pos[string(m[1])] = [2]int{abs(x), abs(y)}
	}
	stockM := stockRe.FindSubmatch(html)
	if stockM == nil {
		fmt.Fprintln(os.Stderr, "no cards_stock")
		os.Exit(1)
	}
	seen := map[string][2]int{}
	for _, qm := range quantCssRe.FindAllSubmatch(stockM[1], -1) {
		for _, seg := range strings.Split(string(qm[1]), ";") {
			for _, tok := range strings.Fields(seg) {
				if p, ok := pos[tok]; ok {
					seen[tok] = p
				}
			}
		}
	}
	am := atlasRe.FindSubmatch(style[1])
	if am == nil {
		fmt.Fprintln(os.Stderr, "no imgunid atlas url")
		os.Exit(1)
	}
	atlas := loadImage(string(am[1]))

	classes := make([]string, 0, len(seen))
	for c := range seen {
		classes = append(classes, c)
	}
	writeMontage(atlas, seen, classes)
	fmt.Println("atlas:", string(am[1]))
	fmt.Println("wrote montage.png; glyphs left-to-right:")
	for i, c := range classes {
		p := seen[c]
		fmt.Printf("  [%d] %s -> %d,%d\n", i, c, p[0], p[1])
	}
	fmt.Println("view montage.png, read the digits, then run: spritecal gen", string(am[1]), "<x,y for 0> ... <x,y for 9>")
}

func writeMontage(atlas image.Image, pos map[string][2]int, order []string) {
	scale, gap := 14, 8
	cw := 7*scale + gap
	out := image.NewRGBA(image.Rect(0, 0, cw*len(order), 15*scale))
	for y := 0; y < out.Bounds().Dy(); y++ {
		for x := 0; x < out.Bounds().Dx(); x++ {
			out.Set(x, y, color.RGBA{40, 40, 40, 255})
		}
	}
	for i, c := range order {
		p := pos[c]
		for dy := 0; dy < 15; dy++ {
			for dx := 0; dx < 7; dx++ {
				col := atlas.At(p[0]+dx, p[1]+dy)
				for sy := 0; sy < scale; sy++ {
					for sx := 0; sx < scale; sx++ {
						out.Set(i*cw+dx*scale+sx, dy*scale+sy, col)
					}
				}
			}
		}
	}
	f, _ := os.Create("montage.png")
	defer f.Close()
	png.Encode(f, out)
}

func gen(atlasSrc string, coords []string) {
	atlas := loadImage(atlasSrc)
	fmt.Println("// Code generated by cmd/spritecal; DO NOT EDIT.")
	fmt.Println("package liga")
	fmt.Println()
	fmt.Println("var digitTemplates = [10][15]uint8{")
	for d := 0; d < 10; d++ {
		x, _ := strconv.Atoi(coords[d*2])
		y, _ := strconv.Atoi(coords[d*2+1])
		rows := rowbits(atlas, x, y)
		fmt.Print("\t{")
		for i, v := range rows {
			if i > 0 {
				fmt.Print(", ")
			}
			fmt.Printf("0x%02x", v)
		}
		fmt.Printf("}, // %d\n", d)
	}
	fmt.Println("}")
}

func rowbits(atlas image.Image, x, y int) [15]uint8 {
	var rows [15]uint8
	for dy := 0; dy < 15; dy++ {
		var b uint8
		for dx := 0; dx < 7; dx++ {
			r, g, bl, _ := atlas.At(x+dx, y+dy).RGBA()
			lum := (299*(r>>8) + 587*(g>>8) + 114*(bl>>8)) / 1000
			if lum > 30 {
				b |= 1 << uint(dx)
			}
		}
		rows[dy] = b
	}
	return rows
}

func abs(v int) int {
	if v < 0 {
		return -v
	}
	return v
}
